# Generated by Django 5.0.4 on 2024-05-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_name_en',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='faq_answer_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='faq_question_en',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='keywords_en',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_name_en',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_text_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_title_en',
            field=models.CharField(default=1, max_length=355),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_description_en',
            field=models.CharField(default=1, max_length=355),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_name_en',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirements',
            name='requirement_text_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirements',
            name='requirement_title_en',
            field=models.CharField(default=1, max_length=355),
            preserve_default=False,
        ),
    ]
