# Generated by Django 4.2 on 2024-05-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0003_category_cat_name_en_faq_faq_answer_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='keywords',
            new_name='keywords_uz',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='paper_name',
            new_name='paper_name_uz',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='paper_text',
            new_name='paper_text_uz',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='paper_title',
            new_name='paper_title_uz',
        ),
        migrations.AddField(
            model_name='paper',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
