# Generated by Django 5.0.4 on 2024-05-19 12:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0005_publication_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='references',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
