# Generated by Django 5.0.4 on 2024-05-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0007_rename_cat_name_category_cat_name_uz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='journal_description',
            new_name='journal_description_uz',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='journal_name',
            new_name='journal_name_uz',
        ),
    ]
